export const surpriseMePrompts = [
  'a rickshaw floating above the Ganges at sunrise, steampunk style',
  'an elephant wearing Bollywood sunglasses and dancing in Times Square',
  'a chaiwala in space serving masala tea to aliens, digital art',
  'a Holi festival celebration on the moon with colorful powder explosions',
  'a royal Bengal tiger meditating in the Himalayas under glowing prayer flags',
  'a Kathakali dancer in a cyberpunk neon-lit alley, digital painting',
  'a saree made of galaxies flowing through a starlit desert in Rajasthan',
  'Lord Ganesha as a robot DJ at an intergalactic rave',
  'a Mumbai local train with windows showing parallel universes',
  'a street vendor selling glowing pani puris in a futuristic Delhi',
  'a peacock riding a bullet train through the Western Ghats',
  'a yoga session led by a monkey guru on top of a digital lotus, vaporwave',
  'a Kumbh Mela procession floating above clouds, celestial illustration',
  'a dosa shaped like a flying saucer hovering over Bengaluru skyline',
  'a Rajasthani puppet doing a TED Talk in front of robots',
  'a 3D render of Taj Mahal made of translucent crystals glowing at night',
  'a Bollywood dance scene underwater with jellyfish backup dancers',
  'a Kathputli puppet show projected as holograms across Jaipur’s palaces',
  'an Indian auto-rickshaw drifting through a video game world',
  'a cow peacefully floating in space with Earth in the background, digital art',
  'a llama DJing at a rooftop party in Rio during carnival',
  'a Viking and a samurai sharing a pizza in New York, comic style',
  'a dragon enjoying ice cream in a Parisian café',
  'a cactus in a suit commuting to work in a neon-lit desert city',
  'a spaceship shaped like a croissant flying over the Eiffel Tower',
  'penguins doing yoga on an iceberg during sunrise',
  'a robot barista serving coffee in a 1920s jazz café',
  'a jellyfish city floating above the Pacific Ocean, bioluminescent light',
  'a koala flying a helicopter made of leaves, Australian outback',
  'a squirrel treasure hunter exploring the Pyramids of Giza',
  'a mermaid video-calling from a coral reef, digital painting',
  'a surrealist painting of Mount Everest made of books',
  'a gothic castle turned into a tech startup HQ',
  'an alien riding a tandem bike with a human through Venice',
  'a panda ice-skating in Central Park in a tuxedo',
  'an ancient Mayan temple transformed into a luxury hotel',
  'a giraffe painting a mural on a skyscraper, perspective from street level',
  'an owl professor giving a TED Talk to robots in a library',
  'a roller coaster made of rainbows through floating islands',
  'a city skyline built on the back of a giant turtle in the ocean'
];
